name: Run tests with Jest
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install required dependencies
        run: npm i -D jest babel-jest @types/jest @babel/preset-typescript @babel/preset-env @babel/core typescript

      - name: Run Jest
        run: npm run test
